### ISSUE TITLE
sync with tibetan-spellchecker

### ISSUE THREAD

**Issue by eroux** [karmapa/checkTibetan_for_ketaka#1]
I think the checker would be more efficient if it was synced with the data in [tibetan-spellchecker](https://github.com/eroux/tibetan-spellchecker/tree/master/syllables). The format is quite easy, each `.txt` contains a list of sequences with (or without) possibility of suffix (for instance `/A`), and [suffixes.json](https://github.com/eroux/tibetan-spellchecker/blob/master/syllables/suffixes.json) contain the different suffixes. The only difference with your current list is that ད་དྲག are not listed in the suffixes. With this data you should be able to generate a new `possible_root_letters_sort.json`. I can make a pull request if you prefer.

**Comment by yapcheahshen** [comment]
Yours is more advance, please do PR.

從我的 iPad 傳送

**Comment by yapcheahshen** [comment]
Directly commit is ok too.
I just grant you write access

從我的 iPad 傳送

**Comment by eroux** [comment]
Ok, closed by https://github.com/karmapa/checkTibetan_for_ketaka/commit/6d605eeb4c5bc950a56cc51c861b436172b6e0bb
